### ISSUE TITLE
BSOD after enabling Virtualization Mode for Dockers

### ISSUE THREAD

**Issue by MarwanTredano** [heroiclabs/nakama-godot-demo#23]
Hi,

to enable Dockers to run, i needed to enable Virtualization mode from the BIOS. 
After that my pc crashed 2 times in a row (Blue Screen, aka BSOD :(   )

Any known fix for this ?
Sorry if this isnt directly related

**Comment by novabyte** [comment]
@MarwanTredano Would really like to help but this issue doesn't have anything to do with Nakama, Godot, or this Godot Multiplayer Demo project repo. Best suggestion I can make is to try to use Docker Toolbox instructions from here:

https://github.com/heroiclabs/nakama-godot-demo/pull/22/files#diff-04c6e90faac2675aa89e2176d2eec7d8R37

**Comment by MarwanTredano** [comment]
Indeed, i wasn't very sure where to go, closing the issue, thanks.
