### ISSUE TITLE
Character is not creating/accessing

### ISSUE THREAD

**Issue by rrbcass** [heroiclabs/nakama-godot-demo#26]
Hi,
I tried to use this demo to study about Nakama and Networking stuff.
I've setup a Nakama Server in a VPS (Ubuntu 19.10) and, so far, it works! I can access Nakama Dashboard and connect using this Demo Client.

The problem is: After a register/connection pops up a Character Creation (Select color and name). After this process our Character isn't created. My list is totally blank:
![image](https://user-images.githubusercontent.com/64291609/83027049-01488800-a006-11ea-8cd7-38cb7d15620b.png)

If I try to 'force' a connection without select a character this error appears:
![image](https://user-images.githubusercontent.com/64291609/83027120-1f15ed00-a006-11ea-8efe-631d3a600b45.png)
I think this is happening because my selection is null.

So, I keep looking at codes and, after unsuccessful tries I decided to working on your tutorial.

It works and, at auth, I used my previous created user (test@test.test) and, for my surprise - at Nakama Dashboard - it creates two characters at user storage. So I thought: lets try to connect now at our Demo Version and:

![image](https://user-images.githubusercontent.com/64291609/83027696-cdba2d80-a006-11ea-8f8a-53cdbdb029fc.png)

I guess there is so connecting problem when we try to access our server.

TY!

**Comment by NathanLovato** [comment]
Sorry, but I don't know why this would happen. We've not had issues with characters in the demo. @Razoric480 would you have any idea?

**Comment by Razoric480** [comment]
When you run the server, do you get the following sort of messages in terminal?
```terminal
nakama         | {"level":"info","ts":"2020-05-27T14:27:23.732Z","msg":"Registered Lua runtime RPC function invocation","id":"get_world_id"}
nakama         | {"level":"info","ts":"2020-05-27T14:27:23.732Z","msg":"Registered Lua runtime RPC function invocation","id":"register_character_name"}
nakama         | {"level":"info","ts":"2020-05-27T14:27:23.732Z","msg":"Registered Lua runtime RPC function invocation","id":"remove_character_name"}
```
`nakama/modules/world_rpc.lua` are where the remote procedures that control character creation and names happen. If they're missing from your server because of some ubuntu-specific sorcery, then yeah, it would fail.

Though that said, you say that they are created in storage, which implies that they do exist, but for some reason can't be accessed by the client. In which case, I am mystified.

**Comment by rrbcass** [comment]
Hi, @Razoric480 and @NathanLovato 
First of all i must appreciate your supporting!

For some reason my Nakama service wasnt loading our modules. I changed this path to './nakama/modules' instead of './nakama/data/modules' and now it is working.
![image](https://user-images.githubusercontent.com/64291609/83039548-b3874c00-a014-11ea-8e1e-30ba920bcc1e.png)

TY!

**Comment by Razoric480** [comment]
♥
