### ISSUE TITLE
The created character does not come to the character list.

### ISSUE THREAD

**Issue by hhuseyincihangir** [heroiclabs/nakama-godot-demo#27]
After logging in with the user and selecting the character color, the character created in the character list does not appear and the game crashes when the login button is pressed. Because there are no characters trying to enter the game by pressing Login.

![resim](https://user-images.githubusercontent.com/15706050/86620423-f7328580-bfc4-11ea-8905-abf94981fad0.png)

**Comment by NathanLovato** [comment]
I can't reproduce this here. Would you have some specific steps to reproduce the bug?

**Comment by olejr** [comment]
Had the problem/symphtom here when I installed Nakama as a standalone server on another machine, not using Docker.

Followed the install/setup instructions from Heroiclabs, and thus not seeing the two lua files in the repo (under nakama/modules).
Those are needed as they suply some custom functions that are used by the demo.

Copied those over to the server, and configured Nakama module path then it's working.

Debugoutput when the crash happened was something like :
```
=== Nakama : DEBUG === Sending request [ID: 5, Method: POST, Uri: http://192.168.1.105:7350/v2/rpc/get_world_id, Headers: {Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhNDQwMGM1Zi02YTRhLTRmMjctYTE5Yi1iMjE5MThhZjQ4NTEiLCJ1c24iOiJvbGVAbWFpbC5ubyIsImV4cCI6MTU5NTE0NjY2Nn0.rL2LM3xg1mrFK1zwFAye1wh1WY1suSQ-CrbP85zX1zY}, Body: "", Timeout: 3]

=== Nakama : DEBUG === Request 5 returned response code: 404, RPC code: 5, error: RPC function not found
```
The _get_world_id_ of the post request here being one of the serverfunctions provided by said lua files..

**Comment by novabyte** [comment]
Thanks @olejr. Sounds like there's no issue here just that the instructions on the README on how to run the server were missed.
