### ISSUE TITLE
Docker image and nakama

### ISSUE THREAD

**Issue by mani144** [heroiclabs/nakama-godot-demo#28]
Greetings,

I was trying to test and learn about Nakama 
however, I failed from the first step which ( setting up Nakama )
once i run docker-compose -f docker-compose.yml up inside nakama folder i get this error :

Creating nakama      ... error

ERROR: for nakama  Cannot create container for service nakama: Conflict. The container name "/nakama" is already in use by container "c08f2e484a16335da155834585e94a1ef9cd09a7550649f74c4faecfab18a59d". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for nakama  Cannot create container for service nakama: Conflict. The container name "/nakama" is already in use by container "c08f2e484a16335da155834585e94a1ef9cd09a7550649f74c4faecfab18a59d". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

I made sure before doing this command that i **dont** have any images or containers

**Comment by mofirouz** [comment]
The error is in the description.

You'll need to run `docker rm -f c08f2e484a16335da155834585e94a1ef9cd09a7550649f74c4faecfab18a59d`
