### ISSUE TITLE
Help me,i need you very much.

### ISSUE THREAD

**Issue by Droog159** [heroiclabs/nakama-godot-demo#29]
I have successfully deployed to the server, but the delay seems to be a bit high, how can I cancel the simulation delay?

**Comment by NathanLovato** [comment]
The delay is here to help you test +/- how a real server will perform. You will need to learn to code to account and compensate for lag, it's part of web development.

Actually, in reality, you're likely to have more delay, at least in the form of spikes, and your game should still function smoothly in that case.

Lag compensation is a complex topic that's beyond the scope of this project so we're not adding it for now.

Also, note these issues are to report bugs, not to ask for support.

**Comment by Droog159** [comment]
> The delay is here to help you test +/- how a real server will perform. You will need to learn to code to account and compensate for lag, it's part of web development.
> 
> Actually, in reality, you're likely to have more delay, at least in the form of spikes, and your game should still function smoothly in that case.
> 
> Lag compensation is a complex topic that's beyond the scope of this project so we're not adding it for now.
> 
> Also, note these issues are to report bugs, not to ask for support.

Thank you for your answer. I mean, did your demo set an analog delay? I heard in your video that you set an analog delay. I want to know where this is and I want to cancel it.
